services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "pnpm prisma generate && npm run dev"

volumes:
  pgdata:
