allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  prisma: true

overrides:
  '@hono/node-server': 1.19.15
  body-parser: 2.3.0
  deepmerge-ts: 8.0.0
  fast-uri: 3.1.5
  hono: 4.12.34
  valibot: 1.4.2
